org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin_version=2.3.20
minecraft_version=26.3-snapshot-8
minecraft_dependency=26.3-alpha.8
loader_version=0.19.3
loom_version=1.15.5
fabric_kotlin_version=1.13.10+kotlin.2.3.20
fabric_api_version=0.157.1+26.3
devauth_version=1.2.2
httpclient_version=4.5.14
classgraph_version=4.8.186
modmenu_version=20.0.0-beta.4
mod_name=quoi!
mod_id=quoi
mod_version=1.1.1
archives_base_name=quoi
