name: Build

on:
  push:
    branches:
      - "26.1.x"
    paths: &build-paths
      - ".gitattributes"
      - ".github/workflows/build.yml"
      - "buildSrc/**"
      - "gradle/**"
      - "src/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "gradlew"
      - "LICENSE"
      - "settings.gradle.kts"
  pull_request:
    paths-ignore: *build-paths

permissions:
  contents: read

concurrency:
  group: build-${{ forgejo.workflow }}-${{ forgejo.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Set Up Java 25
        uses: actions/setup-java@v5.7.0
        with:
          distribution: temurin
          java-version: "25"

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v6.3.0
        with:
          cache-provider: enhanced
          cache-read-only: ${{ forgejo.event_name != 'push' }}
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build Mod
        run: ./gradlew build --build-cache --configuration-cache --stacktrace
        env:
          FORGEJO_TOKEN: ""
          GITHUB_TOKEN: ""

      - name: Upload Build Artifacts
        if: ${{ !cancelled() && (forgejo.event_name != 'pull_request' || failure()) }}
        uses: forgejo/upload-artifact@v4 # v7 is not usable since forgejo only offers up to v4
        with:
          name: quoi-build-artifacts
          path: |
            build/libs/quoi-*.jar
            !build/libs/quoi-*-sources.jar
          if-no-files-found: warn
          compression-level: 0
          retention-days: 14
